export type Settings = {
  ui_language: "system" | "en-US" | "zh-CN";
  agent_provider: "volcengine";
  ai_base_url: string;
  ai_api_key: string;
  ai_model: string;
  agent_api_type: "chat" | "responses";
  professional_field: string;
  research_area: string;
  reader_prompt: string;
  summary_template: string;
  copy_quote_template: string;
  quote_to_note_template: string;
  quote_to_readerm_template: string;
  summary_source: "pdf-direct" | "pdf-extractor" | "latex";
  summary_text_char_limit: number;
  summary_figure_attachment_limit: number;
  capture_image_scale: number;
  markdown_default_font_size: number;
  markdown_line_height: number;
  markdown_code_font_scale: number;
  markdown_code_line_height: number;
  markdown_font_family: string;
  markdown_code_font_family: string;
  markdown_code_line_numbers: boolean;
  markdown_code_ligatures: boolean;
  markdown_highlight_enabled: boolean;
  markdown_highlight_color: string;
  markdown_math_enabled: boolean;
  markdown_html_live_enabled: boolean;
  markdown_default_editor_mode: "edit" | "live" | "preview";
  readerm_edit_split_default: boolean;
  readerm_preview_position: "right" | "bottom";
  history_readerp_link_view: "pdf" | "markdown" | "summary";
  ai_send_notes_context: boolean;
  ai_send_summary_context: boolean;
  ai_send_annotations_context: boolean;
  ai_send_loaded_pdf_text: boolean;
  ai_send_figure_attachments: boolean;
  simpletex_ocr_token: string;
  simpletex_ocr_enabled: boolean;
  translator_mode: "ai" | "api";
  translation_provider: "google" | "baidu";
  translator_api_url: string;
  translator_api_key: string;
  translator_target_language: string;
  google_project_id: string;
  google_api_key: string;
  baidu_app_id: string;
  baidu_app_key: string;
  network_proxy_enabled: boolean;
  network_proxy_url: string;
};
