export type Settings = {
  ui_language: "system" | "en-US" | "zh-CN";
  agent_provider: "volcengine";
  ai_base_url: string;
  ai_api_key: string;
  ai_model: string;
  agent_api_type: "chat" | "responses";
  professional_field: string;
  research_area: string;
  reader_prompt: string;
  summary_template: string;
  summary_source: "pdf-direct" | "pdf-extractor" | "latex";
  summary_figure_attachment_limit: number;
  ai_send_notes_context: boolean;
  ai_send_summary_context: boolean;
  ai_send_annotations_context: boolean;
  ai_send_loaded_pdf_text: boolean;
  ai_send_figure_attachments: boolean;
  translator_mode: "ai" | "api";
  translation_provider: "google" | "baidu";
  translator_api_url: string;
  translator_api_key: string;
  translator_target_language: string;
  google_project_id: string;
  google_api_key: string;
  baidu_app_id: string;
  baidu_app_key: string;
  network_proxy_enabled: boolean;
  network_proxy_url: string;
};
